namespace P7_UrbanRead
{
    enum GenreType
    {
        Fiction,
        NonFiction,
        Fantasy,
        ScienceFiction,
        Action,
        Adventure,
        Mystery,
        Horror,
        Thriller,
        Suspense,
        Historical,
        Romance,
        GraficNovel,
        LGBTQ,
        YoungAdult,
        Children,
        Poetry,
        Fairytale,
        Drama,
        MemoirAutobiography,
        Diary,
        Dictionary,
        Biography,
        FoodDrink,
        SelfHelp,
        History,
        Travel,
        TrueCrime,
        Humor,
        HowTo_Guide,
        ReligionSpirituality,
        Parenting,
        ScienceTechnology
        
    }
}