namespace P7_UrbanRead
{
    //Google Book uses BISAC book genre code for category classification (https://support.google.com/books/partner/answer/3237055?hl=en)
    //BISAC simplified list (https://www.bisg.org/complete-bisac-subject-headings-list)
    //BISAC full list (https://gist.github.com/jveldboom/6542197)
    enum GenreType
    {
        Antiques_Collectibles,
        Architecture,
        Art,
        Bibles,
        Biography_Autobiography,
        Body_Mind_Spirit,
        Business_Economics,
        Comics_GraphicNovels,
        Computers,
        Cooking,
        Crafts_Hobbies,
        Design,
        Drama,
        Education,
        Family_Relationships,
        Fiction,
        ForeignLanguageStudy,
        Future,
        Games_Activities,
        Gardening,
        Health_Fitness,
        History,
        House_Home,
        Humor,
        JuvenileFiction,
        JuvenileNonFiction,
        LanguageArts_Disciplines,
        Law,
        LiteraryCollections,
        LiteraryCriticism,
        Mathematics,
        Medical,
        Music,
        Nature,
        PerformingArts,
        Pets,
        Philosophy,
        Photography,
        Poetry,
        PoliticalScience,
        Psychology,
        Reference,
        Religion,
        Science,
        SelfHelp,
        SocialScience,
        Sports_Recreation,
        StudyAids,
        Technology_Engineering,
        Transportation,
        Travel,
        TrueCrime,
        YoungAdultFiction,
        YoungAdultNonFiction,
        
    }
}