    <Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-WebUI-1673EB5E-6551-40C8-BE84-DDA778FC446A</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\NewFolder\**" />
    <Content Remove="Areas\NewFolder\**" />
    <EmbeddedResource Remove="Areas\NewFolder\**" />
    <None Remove="Areas\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\BookSearchService.cs" />
    <Compile Remove="Migrations\20240526045724_mssql.local_migration_681.cs" />
    <Compile Remove="Migrations\20240526045724_mssql.local_migration_681.Designer.cs" />
    <Compile Remove="Migrations\20240529032231_202405281121_mssql.local_migration_001.cs" />
    <Compile Remove="Migrations\20240529032231_202405281121_mssql.local_migration_001.Designer.cs" />
    <Compile Remove="Migrations\20240605005029_mssql.local_migration_002.cs" />
    <Compile Remove="Migrations\20240605005029_mssql.local_migration_002.Designer.cs" />
    <Compile Remove="Migrations\20240917130622_WebUIUser.cs" />
    <Compile Remove="Migrations\20240917130622_WebUIUser.Designer.cs" />
    <Compile Remove="Migrations\20241021110346_mssql.local_migration_694.cs" />
    <Compile Remove="Migrations\20241021110346_mssql.local_migration_694.Designer.cs" />
    <Compile Remove="Migrations\20241021111943_mssql.local_migration_603.cs" />
    <Compile Remove="Migrations\20241021111943_mssql.local_migration_603.Designer.cs" />
    <Compile Remove="Migrations\20241022112709_mssql.local_migration_979.cs" />
    <Compile Remove="Migrations\20241022112709_mssql.local_migration_979.Designer.cs" />
    <Compile Remove="Migrations\20250123035430_mssql_migration_618.cs" />
    <Compile Remove="Migrations\20250123035430_mssql_migration_618.Designer.cs" />
    <Compile Remove="Migrations\20250123040348_mssql.local_migration_251.cs" />
    <Compile Remove="Migrations\20250123040348_mssql.local_migration_251.Designer.cs" />
    <Compile Remove="Migrations\WebUIContextModelSnapshot.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="BookDetails.razor.razor" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.5" />
	<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.5" />
	  
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\P7_UrbanRead\P7_UrbanRead.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
